permissions:
  contents: write

on:
  workflow_dispatch:
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git subtree pull --prefix=Packages/com.merlin.UdonSharp https://github.com/uwx/USharpSplit main
          git push -u origin master
